import csv
import io
import json
from typing import Any, Dict


class ExportService:
    """Service to export reports to JSON and CSV formats (extensible)."""

    EXPORT_VERSION = "1.0"

    @classmethod
    def export_executive_report_json(cls, report_data: Dict[str, Any]) -> str:
        """Export executive report to JSON format."""
        from datetime import datetime, timezone

        wrapped = {
            "report_version": cls.EXPORT_VERSION,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "generated_by": "AegisX",
            "data": report_data,
        }
        return json.dumps(wrapped, indent=2)

    @classmethod
    def export_asset_report_json(cls, report_data: Dict[str, Any]) -> str:
        """Export asset report to JSON format."""
        from datetime import datetime, timezone

        wrapped = {
            "report_version": cls.EXPORT_VERSION,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "generated_by": "AegisX",
            "data": report_data,
        }
        return json.dumps(wrapped, indent=2)

    @classmethod
    def export_executive_report_csv(cls, report_data: Dict[str, Any]) -> str:
        """Export executive report to a structured CSV format."""
        from datetime import datetime, timezone

        output = io.StringIO()
        output.write(f"# Report Version: {cls.EXPORT_VERSION}\n")
        output.write("# Generated By: AegisX\n")
        output.write(f"# Generated At: {datetime.now(timezone.utc).isoformat()}\n")
        writer = csv.writer(output)

        # 1. Summary Section
        writer.writerow(["Section", "Metric", "Value"])
        summary = report_data.get("summary", {})
        writer.writerow(["Summary", "Asset Count", summary.get("asset_count", 0)])
        writer.writerow(
            [
                "Summary",
                "Internet Exposed Assets",
                summary.get("internet_exposed_assets", 0),
            ]
        )
        writer.writerow(["Summary", "Open Ports", summary.get("open_ports", 0)])
        writer.writerow(["Summary", "Services", summary.get("services", 0)])

        # 2. Risk Distribution
        risk_dist = report_data.get("risk_distribution", {})
        for level, cnt in risk_dist.items():
            writer.writerow(["Risk Distribution", f"Risk Level: {level}", cnt])

        # 3. Exposure Distribution
        exp_dist = report_data.get("exposure_distribution", {})
        for classification, cnt in exp_dist.items():
            writer.writerow(["Exposure Distribution", classification, cnt])

        writer.writerow([])  # Empty line separator

        # 4. Top Risky Assets Section
        writer.writerow(
            [
                "Top Risky Assets - ID",
                "Host",
                "IP",
                "Type",
                "Risk Score",
                "Risk Level",
                "Criticality",
            ]
        )
        for asset in report_data.get("top_risky_assets", []):
            writer.writerow(
                [
                    asset.get("id"),
                    asset.get("host"),
                    asset.get("ip"),
                    asset.get("asset_type"),
                    asset.get("risk_score"),
                    asset.get("risk_level"),
                    asset.get("criticality"),
                ]
            )

        writer.writerow([])  # Empty line separator

        # 5. Critical Findings Section
        writer.writerow(
            [
                "Critical Findings - ID",
                "Asset ID",
                "Title",
                "Severity",
                "Status",
                "Template ID",
            ]
        )
        for finding in report_data.get("critical_findings", []):
            writer.writerow(
                [
                    finding.get("id"),
                    finding.get("asset_id"),
                    finding.get("title"),
                    finding.get("severity"),
                    finding.get("status"),
                    finding.get("template_id"),
                ]
            )

        return output.getvalue()

    @classmethod
    def export_asset_report_csv(cls, report_data: Dict[str, Any]) -> str:
        """Export asset report to a structured CSV format."""
        from datetime import datetime, timezone

        output = io.StringIO()
        output.write(f"# Report Version: {cls.EXPORT_VERSION}\n")
        output.write("# Generated By: AegisX\n")
        output.write(f"# Generated At: {datetime.now(timezone.utc).isoformat()}\n")
        writer = csv.writer(output)

        # 1. Asset Details Section
        writer.writerow(["Section", "Property", "Value"])
        asset = report_data.get("asset", {})
        writer.writerow(["Asset Details", "ID", asset.get("id")])
        writer.writerow(["Asset Details", "Scope ID", asset.get("scope_id")])
        writer.writerow(["Asset Details", "Host", asset.get("host")])
        writer.writerow(["Asset Details", "IP", asset.get("ip")])
        writer.writerow(["Asset Details", "Type", asset.get("asset_type")])
        writer.writerow(["Asset Details", "First Seen", asset.get("first_seen")])
        writer.writerow(["Asset Details", "Last Seen", asset.get("last_seen")])

        # 2. Exposure Section
        exp = report_data.get("exposure", {})
        writer.writerow(["Exposure", "Classification", exp.get("classification")])
        writer.writerow(
            ["Exposure", "Risk Factors", "; ".join(exp.get("risk_factors", []))]
        )

        # 3. Risk Section
        risk = report_data.get("risk", {})
        writer.writerow(["Risk", "Score", risk.get("risk_score")])
        writer.writerow(["Risk", "Level", risk.get("risk_level")])
        writer.writerow(["Risk", "Criticality", risk.get("criticality")])

        writer.writerow([])  # Empty line separator

        # 4. Open Ports Section
        writer.writerow(
            ["Open Ports - ID", "Port", "Protocol", "State", "First Seen", "Last Seen"]
        )
        for port in report_data.get("ports", []):
            writer.writerow(
                [
                    port.get("id"),
                    port.get("port"),
                    port.get("protocol"),
                    port.get("state"),
                    port.get("first_seen"),
                    port.get("last_seen"),
                ]
            )

        writer.writerow([])  # Empty line separator

        # 5. Services Section
        writer.writerow(
            [
                "Services - ID",
                "Port",
                "Service Name",
                "Product",
                "Version",
                "Banner",
                "Confidence",
            ]
        )
        for svc in report_data.get("services", []):
            writer.writerow(
                [
                    svc.get("id"),
                    svc.get("port"),
                    svc.get("service_name"),
                    svc.get("product"),
                    svc.get("version"),
                    svc.get("banner"),
                    svc.get("confidence"),
                ]
            )

        writer.writerow([])  # Empty line separator

        # 6. Technologies Section
        writer.writerow(["Technologies", "Name"])
        for tech in report_data.get("technologies", []):
            writer.writerow(["Technologies", tech])

        writer.writerow([])  # Empty line separator

        # 7. Active Findings Section
        writer.writerow(
            [
                "Findings - ID",
                "Title",
                "Severity",
                "Status",
                "Template ID",
                "Template Name",
                "Plugin",
            ]
        )
        for finding in report_data.get("findings", []):
            writer.writerow(
                [
                    finding.get("id"),
                    finding.get("title"),
                    finding.get("severity"),
                    finding.get("status"),
                    finding.get("template_id"),
                    finding.get("template_name"),
                    finding.get("source_plugin"),
                ]
            )

        return output.getvalue()
