"""sprint_37_6b_phase2

Revision ID: 49a03efe9402
Revises: 550eeb9a3a3c
Create Date: 2026-07-05 14:04:49.810355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49a03efe9402'
down_revision: Union[str, None] = '550eeb9a3a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_intelligence_graph_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_intelligence_edges',
    sa.Column('edge_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('edge_fingerprint', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('edge_type', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('edge_id'),
    sa.UniqueConstraint('edge_fingerprint')
    )
    op.create_table('security_intelligence_nodes',
    sa.Column('node_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('node_fingerprint', sa.String(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('node_id'),
    )
    # Apply RLS & Force RLS to the new tables
    for table in ['security_intelligence_nodes', 'security_intelligence_edges', 'security_intelligence_graph_history']:
        op.execute(sa.text(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY"))
        op.execute(sa.text(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY"))
        op.execute(
            sa.text(
                f"""
                CREATE POLICY tenant_isolation ON {table}
                USING (tenant_id = COALESCE(NULLIF(current_setting('app.current_tenant', true), '')::uuid, '00000000-0000-0000-0000-000000000000'::uuid))
                """
            )
        )

    op.add_column('threat_intel_actors', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('threat_intel_actors', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('threat_intel_actors', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('threat_intel_actors', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('threat_intel_actors', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('threat_intel_actors', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('threat_intel_actors', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('threat_intel_actors', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'threat_intel_actors', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'threat_intel_actors', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'threat_intel_actors', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.add_column('threat_intel_campaigns', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('threat_intel_campaigns', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('threat_intel_campaigns', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('threat_intel_campaigns', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('threat_intel_campaigns', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('threat_intel_campaigns', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('threat_intel_campaigns', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('threat_intel_campaigns', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'threat_intel_campaigns', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'threat_intel_campaigns', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'threat_intel_campaigns', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.add_column('threat_intel_history', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('threat_intel_history', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('threat_intel_history', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('threat_intel_history', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'threat_intel_history', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'threat_intel_history', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.add_column('threat_intel_iocs', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('threat_intel_iocs', sa.Column('tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('threat_intel_iocs', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('threat_intel_iocs', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('threat_intel_iocs', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('threat_intel_iocs', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('threat_intel_iocs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('threat_intel_iocs', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'threat_intel_iocs', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'threat_intel_iocs', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'threat_intel_iocs', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'threat_intel_iocs', type_='foreignkey')
    op.drop_constraint(None, 'threat_intel_iocs', type_='foreignkey')
    op.drop_constraint(None, 'threat_intel_iocs', type_='foreignkey')
    op.drop_column('threat_intel_iocs', 'deleted_by')
    op.drop_column('threat_intel_iocs', 'deleted_at')
    op.drop_column('threat_intel_iocs', 'is_deleted')
    op.drop_column('threat_intel_iocs', 'version')
    op.drop_column('threat_intel_iocs', 'updated_by')
    op.drop_column('threat_intel_iocs', 'created_by')
    op.drop_column('threat_intel_iocs', 'tags')
    op.drop_column('threat_intel_iocs', 'confidence')
    op.drop_constraint(None, 'threat_intel_history', type_='foreignkey')
    op.drop_constraint(None, 'threat_intel_history', type_='foreignkey')
    op.drop_column('threat_intel_history', 'updated_by')
    op.drop_column('threat_intel_history', 'created_by')
    op.drop_column('threat_intel_history', 'updated_at')
    op.drop_column('threat_intel_history', 'created_at')
    op.drop_constraint(None, 'threat_intel_campaigns', type_='foreignkey')
    op.drop_constraint(None, 'threat_intel_campaigns', type_='foreignkey')
    op.drop_constraint(None, 'threat_intel_campaigns', type_='foreignkey')
    op.drop_column('threat_intel_campaigns', 'deleted_by')
    op.drop_column('threat_intel_campaigns', 'deleted_at')
    op.drop_column('threat_intel_campaigns', 'is_deleted')
    op.drop_column('threat_intel_campaigns', 'version')
    op.drop_column('threat_intel_campaigns', 'updated_by')
    op.drop_column('threat_intel_campaigns', 'created_by')
    op.drop_column('threat_intel_campaigns', 'updated_at')
    op.drop_column('threat_intel_campaigns', 'created_at')
    op.drop_constraint(None, 'threat_intel_actors', type_='foreignkey')
    op.drop_constraint(None, 'threat_intel_actors', type_='foreignkey')
    op.drop_constraint(None, 'threat_intel_actors', type_='foreignkey')
    op.drop_column('threat_intel_actors', 'deleted_by')
    op.drop_column('threat_intel_actors', 'deleted_at')
    op.drop_column('threat_intel_actors', 'is_deleted')
    op.drop_column('threat_intel_actors', 'version')
    op.drop_column('threat_intel_actors', 'updated_by')
    op.drop_column('threat_intel_actors', 'created_by')
    op.drop_column('threat_intel_actors', 'updated_at')
    op.drop_column('threat_intel_actors', 'created_at')
    for table in ['security_intelligence_nodes', 'security_intelligence_edges', 'security_intelligence_graph_history']:
        op.execute(sa.text(f"DROP POLICY IF EXISTS tenant_isolation ON {table}"))
        op.execute(sa.text(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY"))
        op.execute(sa.text(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY"))

    op.drop_table('security_intelligence_nodes')
    op.drop_table('security_intelligence_edges')
    op.drop_table('security_intelligence_graph_history')
    # ### end Alembic commands ###
