"""add_related_entities_to_hunts

Revision ID: 8e2fe6d6496f
Revises: d2dadc500f3c
Create Date: 2026-07-05 18:53:21.838105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e2fe6d6496f'
down_revision: Union[str, None] = 'd2dadc500f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hunts', sa.Column('related_entities', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hunts', 'related_entities')
    # ### end Alembic commands ###
