"""add_asset_finding_to_remediations

Revision ID: d2dadc500f3c
Revises: ea0a5b45648c
Create Date: 2026-07-05 18:50:51.807272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2dadc500f3c'
down_revision: Union[str, None] = 'ea0a5b45648c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remediations', sa.Column('asset_id', sa.UUID(), nullable=False))
    op.add_column('remediations', sa.Column('finding_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'remediations', 'assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'remediations', 'findings', ['finding_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('scopes_owner_id_name_key'), 'scopes', type_='unique')
    op.alter_column('security_intelligence_fabric_propagations', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('security_intelligence_fabric_propagations', 'decay_factor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'security_intelligence_nodes', ['node_fingerprint'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'security_intelligence_nodes', type_='unique')
    op.alter_column('security_intelligence_fabric_propagations', 'decay_factor',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('security_intelligence_fabric_propagations', 'confidence_score',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.create_unique_constraint(op.f('scopes_owner_id_name_key'), 'scopes', ['owner_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'remediations', type_='foreignkey')
    op.drop_constraint(None, 'remediations', type_='foreignkey')
    op.drop_column('remediations', 'finding_id')
    op.drop_column('remediations', 'asset_id')
    # ### end Alembic commands ###
